### ISSUE TITLE
简单好用 已收纳 发现个小bug

### ISSUE THREAD

**Issue by junlv** [shadowOfCode/bee.js#6]
emailRegexs: {
			EMAIL_PATTERN: /^[-\w\+]+(?:\.[-\w]+)*@[-a-z0-9]+(?:\.[a-z0-9]+)*(?:\.[a-z]{2,})$/i
		},
		//邮箱格式校验
		isEmail: function(input) {
			return this. emailRegexs .EMAIL_PATTERN.test(input); // 这里
		}

**Comment by shadowOfCode** [comment]
您说，具体是什么问题

**Comment by junlv** [comment]
return this.EMAIL_PATTERN.test(input); ==> this. emailRegexs .EMAIL_PATTERN.test(input); // 这里

**Comment by shadowOfCode** [comment]
非常感谢！写的时候大意了
